import NavBar from "@/components/navbar/NavBar";
import "./globals.css";
import Footer from "@/components/footer/Footer";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className='font-roboto flex flex-col justify-between h-screen w-5/6 m-auto p-6'>
				<NavBar />
				{children}
				<Footer />
			</body>
		</html>
	);
}
